sonar.projectKey=imx462-rpi-controller
sonar.projectName=imx462-rpi-controller
sonar.python.version=3.9,3.11,3.12,3.13
sonar.sources=src,scripts
sonar.tests=tests
sonar.coverage.exclusions=**
sonar.exclusions=**/.venv/**,**/__pycache__/**,**/build/**,**/dist/**,**/samples/**,**/docs/**,**/ansible/**,**/openspec/**,tests,tests/**
