sonar.projectKey=kamkry-zz_imx462-rpi-controller_959a75ba-70f3-4230-8762-55f97d4d38a1
sonar.projectName=imx462-rpi-controller
sonar.python.version=3.9,3.11,3.12,3.13
sonar.sources=src,scripts
sonar.tests=tests
sonar.coverage.exclusions=**
sonar.exclusions=**/.venv/**,**/__pycache__/**,**/build/**,**/dist/**,**/samples/**,**/docs/**,**/ansible/**,**/openspec/**,tests,tests/**
